spring:
  datasource:
    url: jdbc:mysql://39.105.65.229:3306/jwt?useUnicode=true&characterEncoding=utf8
    name: root
    password: 123456




logging:
  level:
    com:
      example:
        security:
          mapper: debug
  config: classpath:logback.xml